name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - run: dotnet build --configuration Release
